### ISSUE TITLE
Requested URL Not Found

### ISSUE THREAD

**Issue by LPX55** [sarangnx/torrent-server#4]
Can't seem to deploy on Ubuntu 18 -- the server is running fine, I get no error messages on the backend. I set my port and all my envs are correct, but when I browse over, I get error:

`{"message":"Requested URL Not Found"}` 

Seems like a routing issue?

The demo heroku app is showing the same error as well https://bp-torrent.herokuapp.com/ 😅

**Comment by sarangnx** [comment]
The frontend was in a seperate repo: https://github.com/sarangnx/torrent-webapp 
In case of the 404 message, there is no handler set for '/' route. 😄

This was just a fun side project built on top of https://github.com/webtorrent/webtorrent

**Comment by LPX55** [comment]
LOL, whoops :)
